#!/usr/bin/env bash
# One VOD feed at a time — continuous loop, flock prevents duplicates.
set -Eeuo pipefail
set -a
source /root/.video_bot.env
set +a
export MLBB_VOD_RELIABLE=1
export MLBB_TEAMFIGHT_ABS_FLOOR=0.30
export MLBB_TEAMFIGHT_RANK_FRAC=0.75
export MLBB_MOTION_PEAK_MAX=4
export MLBB_TEAMFIGHT_MIN_SCORE=0.45
export VIRAL_MLBB_CLIP_HOOK_MIN=0.18
export HIGHLIGHT_MLBB_AUTO_CLIP_MIN=0.12
export MLBB_RULE_COMBAT_MIN=0.85
export MLBB_VOD_TRIM_MAX_FRAC=0.35
export MLBB_BANNER_HARD_POST_CUT=1
export MLBB_FIGHT_POST_SEC=2.0
export MLBB_BANNER_POST_SEC=2.0
export MLBB_DOUBLE_BANNER_POST_SEC=4.0
export MLBB_TRIPLE_BANNER_POST_SEC=5.0
export MLBB_STREAK_BANNER_POST_SEC=5.5
export MLBB_RERENDER_ON_BANNER_OFF=1
export MLBB_VOD_TRIM_MOTION_ANCHOR=0
export MLBB_VOD_MAX_ZERO_ATTEMPTS=1
export MLBB_VOD_BANNER_SKIP_ON_MISS=1
export MLBB_VOD_SEND_ONE=0
export MLBB_VOD_PRESEND_SKIP_VISUAL_ON_BANNER=1
export MLBB_KILL_BANNER_REQUIRED=1
export MLBB_VOD_BANNER_PRESEND=0
export MLBB_VOD_MOTION_ANCHOR_OK=0
export MLBB_BANNER_REF_MATCH=1
export MLBB_BANNER_POS_REF_MATCH=1
export MLBB_BANNER_REF_BEFORE_OCR=1
export MLBB_BANNER_OCR_FUZZY_MIN=0.72
export MLBB_BANNER_REF_REQUIRE_OCR=1
export MLBB_BANNER_RAPID_OCR=1
export MLBB_BANNER_POS_INCLUDE_VOD_CROPS=0
export MLBB_BANNER_POS_REF_MIN_SIM=0.45
export MLBB_KILL_BANNER_DISCOVER_MAX_PROBES=20
export MLBB_KILL_BANNER_DISCOVER_SPIKE_CAP=24
export VIRAL_COMBAT_HOOK_MIN=0.06
export SHOOTER_VOD_DELETE_EXHAUSTED=1
export SHOOTER_VOD_MAX_ZERO_ATTEMPTS=1
export PUBG_VOD_MONTAGE=0
export SHOOTER_VOD_MONTAGE=0
export SHOOTER_VOD_DOWNLOAD_NOTIFY=0
export SHOOTER_VOD_DISCOVERY_MISS_NOTIFY=0
export SHOOTER_VOD_EXHAUST_NOTIFY=0
export SHOOTER_VOD_ADAPTIVE_NOTIFY=0
export SHOOTER_VOD_RELIABLE=1
export SHOOTER_VOD_MAX_SEC=1200
export VIRAL_SEGMENT_HOOK_MIN=0.08
export SHOOTER_VOD_METRO_REJECT_NOTIFY=0
export SHOOTER_VOD_FAST_PROBE_MAX=10
export SHOOTER_VOD_FAST_PANN_MIN=0.08
export PUBG_COMBAT_FRAMES_REQUIRED=2
export PUBG_COMBAT_PANN_MIN=0.14
export HIGHLIGHT_PANN_FIXED=0
export HIGHLIGHT_PANN_INFERENCE_FLOOR=0.10
export HIGHLIGHT_PANN_GUN_MIN=0.15
export SMART_LONG_WINDOW_SEC=1.0
export SMART_LONG_ANALYSIS_MAX_FPS=2.0
export SMART_LONG_SAMPLE_FPS=2.0
export SMART_SAMPLE_FPS=4.0
export SMART_ANALYSIS_DETAIL=max
export CONTENT_BOT_REPO=/root/content_bot_ml
export PYTHONPATH="/usr/local/bin:${CONTENT_BOT_REPO}/scripts"
export HIGHLIGHT_HEATMAP=0
export MLBB_ONLY_MODE=1
export MLBB_VOD_ONLY=1
export MLBB_VOD_DISABLED=0
export MLBB_CALIBRATION_FEED_ENABLED=0
export MLBB_VOD_NO_CROP=1
export MLBB_VOD_LANDSCAPE=1
export MLBB_VOD_OUT_WIDTH=1280
export MLBB_VOD_OUT_HEIGHT=720
export MLBB_VOD_VARIABLE_LENGTH=1
export MLBB_VOD_OWNER_EXEMPLARS=0
export MLBB_VOD_YIELD_MEMORY_ENABLED=1
export HIGHLIGHT_USE_OWNER_ANCHORS=0
export VOD_CALIBRATION_SEND_AS_FILE=1
export HIGHLIGHT_CLIP_DISABLED=1
export MLBB_VOD_SEND_ONE=0
export MLBB_VOD_BATCH_MAX=0
export MLBB_VOD_INTERVAL_GAP_SEC=3
export MLBB_VOD_PIPELINE_MAX_VODS=0
export MLBB_VOD_PIPELINE_MAX_MIN=0
export MLBB_VOD_PROBE_LIMIT=24
export MLBB_VOD_SEGMENT_GAP_SEC=45
export MLBB_FIGHT_MAX_SEC=55
export MLBB_FIGHT_HARD_MAX_SEC=65
export MLBB_FIGHT_TRIM_LONG=0
export HIGHLIGHT_MAX_PANN_PROBE=5
export HIGHLIGHT_MAX_STAGE1=16
export HIGHLIGHT_PARALLEL_WORKERS=6
export SMART_FFMPEG_THREADS=6
export MLBB_VOD_MIN_PEAK_SEC=20
export MLBB_VOD_SKIP_REVALIDATE=1
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export LOGO_FILE=/nonexistent/mlbb_calibration_no_logo.png
unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy
IDLE_SEC="${MLBB_VOD_IDLE_SEC:-25}"

# Soft banner gates — YouTube OCR is often blind; do not override with 0.62/1.25.
export MLBB_BANNER_REF_COLOR_MUL=0.90
export MLBB_BANNER_POS_LIVE_MIN_SIM=0.58
export MLBB_BANNER_OWNER_GATE=0
export MLBB_BANNER_SEND_STRICT=0
# 90s left only ~2 OCR peak probes then abort; 180s lets miss→OCR spike finish.
export MLBB_KILL_BANNER_DISCOVER_MAX_SEC=180
export MLBB_KILL_BANNER_DISCOVER_TITLE_CAP=1
export MLBB_KILL_BANNER_DISCOVER_STEP=2
export MLBB_KILL_BANNER_DISCOVER_MAX_PROBES=20

# MLBB daily montages: 3–4 double+ fights → one Telegram video

# MLBB daily montages: 3-4 double+ fights -> one Telegram video
export MLBB_VOD_MONTAGE=1
export MLBB_SKIP_MONTAGE=0
export MLBB_VOD_MONTAGE_MIN_TIER=single
export MLBB_VOD_MONTAGE_MIN_CLIPS=1
export MLBB_VOD_MONTAGE_MAX_CLIPS=4
export MLBB_VOD_SEND_ALL_BANNERS=1
export MLBB_VOD_MAX_PER_VOD=2

# Runtime knobs (must be BEFORE the loop — trailing exports never ran)
export MLBB_FIGHT_FIRST_ABORT_ON_MISS=1
export MLBB_KILL_BANNER_DISCOVER_MIN_HITS=1
export MLBB_KILL_BANNER_DISCOVER_TARGET=2
export MLBB_DISCOVER_SHIP_ON_FIRST=1
export MLBB_BANNER_SKIP_CLIP_SCORE=1
export MLBB_KILL_DISCOVER_ALLOW_OCR=1
# 0 historically starved miss→spike (ref-only). Allow a few OCR spikes on miss path.
export MLBB_KILL_BANNER_DISCOVER_OCR_SPIKES=3
export MLBB_VOD_PROMOTE_HOLD=1
export MLBB_VOD_AUTO_DOWNLOAD_ON_EMPTY=1
# AUTO_DOWNLOAD=1 — do not leave inbox starved on exhausted/yield-dead files.

export MLBB_BANNER_DISCOVER_POS_LIVE_MIN_SIM=0.55
export MLBB_BANNER_DISCOVER_OWN_KILL_MIN_SIM=0.55
export MLBB_BANNER_NEG_POS_MARGIN=0.06
export MLBB_BANNER_LIVE_OVERLAY_OCR=1
export MLBB_BANNER_OWN_HUD_MIN_SIM=0.17
export MLBB_OCR_DOUBLE_REQUIRE_LIVE=1
export MLBB_VOD_AUTO_DOWNLOAD=1
export MLBB_VOD_BANNER_HARD_PREFILTER=1

export MLBB_BANNER_DISCOVER_RAPID_PEAKS=1
export MLBB_BANNER_DISCOVER_RAPID=0
export MLBB_VOD_PREFETCH=1
export MLBB_VOD_INBOX_MAX=3
export MLBB_VOD_PRESEND_COOLDOWN_SEC=60
export MLBB_VOD_ZERO_SEND_COOLDOWN_SEC=90
export MLBB_VOD_SCAN_COOLDOWN_SEC=120
export MLBB_VOD_PEAK_POOL_MAX_AGE_SEC=60
export MLBB_VOD_REUSE_PEAK_POOL=0

export MLBB_VOD_KEEP_BANNER_MISS=1
export MLBB_VOD_REUSE_PEAK_POOL=0
export VOD_POOL_TTL_SEC=900
export MLBB_PRESEND_OWN_KILL_SINGLE=1
export MLBB_PRESEND_LIVE_OCR_BUDGET=4
export MLBB_PRESEND_RAPID_OCR_TIMEOUT_SEC=8
export MLBB_PRESEND_OWN_KILL_NEIGHBOR_OFFS=-1,1,2
export MLBB_FIGHT_FIRST_KILL_RICH_SPIKE_SEC=90
export MLBB_FIGHT_FIRST_KILL_RICH_SPIKE_PROBES=12
export MLBB_VOD_INBOX_EXHAUSTED_MAX=1
export MLBB_VOD_REVIVE_MAX_FORCE=1
# Shooters inherit this launcher env via daily_cycle_runner — scrub CLIP-off there.
# Keep MLBB CLIP-off here; runner clears HIGHLIGHT_CLIP_DISABLED for pubg/standoff.

while true; do
  python3 -u /usr/local/bin/daily_cycle_runner.py \
    >>/root/data/mlbb/mlbb_vod_segment_feed.log 2>&1 || true
  sleep "$IDLE_SEC"
done
